name: Build and Push Docker Image
on:
  workflow_call:
    inputs:
      docker_repo_name:
        description: 'Name of the Docker Hub repository (e.g., mukesh18s/prod)'
        required: true
        type: string
      DOCKERHUB_USERNAME:
        required: true
        type: string
      DOCKERHUB_PASSWORD:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ inputs.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE_NAME=${{ inputs.docker_repo_name }}
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
